### PR TITLE
feat: viz integration

### PR DESCRIPTION
**Pull request by fundon**
Viz is a fast, flexible, lightweight web framework.

Repo: https://github.com/viz-rs/viz
Website: https://viz.rs/

* [x] leptos-viz
* [x] examples

If you don't think it makes sense to put it in the leptos project, you can close it. :)

### CODE REVIEW

**Comment by gbj** [comment]
Cool! Are you still working on the integration or is this ready to review?

**Comment by fundon** [comment]
I'm done updating and ready to review.

**Comment by gbj** [comment]
Thanks for your work on this. I'm not very familiar with Viz, but it looks like the internals are very similar to Axum... diffing this against the Axum integration it looks like there's a lot of shared code that could probably do with a refactor. Same goes for the examples, of course.

I'm working on another PR that is already doing some refactoring of the integrations, so I'm happy to take this as is for now, and handle the refactoring as part of that other work.

On the examples, on the other hand — rather than duplicating three existing examples, could you please pick one to highlight Viz and remove the other two? This will reduce the maintenance burden for me over time if and when we need to update the application code in examples.

**Comment by gbj** [comment]
@fundon I've merged the other PR — So if you compare what you did for `leptos_viz` to the version of `leptos_axum` that's in `main` now, you should be able to apply more or less the same set of changes you did earlier, and get support for in-order streaming and async rendering out of the box. I wasn't able to refactor quite as much as I'd hoped but every bit counts. Let me know if you run into any issues and I hope this doesn't cause you to duplicate too much of your work.

**Comment by fundon** [comment]
@gbj I have merged the latest changes and only keep the sqlite example. 

If you come across viz related later, you can tell me and I can maintain this part of the code. :)

**Comment by gbj** [comment]
Thanks! This is great.

The doctests are failing on
```
---- src/lib.rs - render_app_async (line 746) stdout ----
error[E0423]: expected function, tuple struct or tuple variant, found struct `ServiceMaker`
  --> src/lib.rs:776:16
   |
33 |         .serve(ServiceMaker(app))
   |                ^^^^^^^^^^^^^^^^^ help: use struct literal syntax instead: `ServiceMaker { tree: val }`
   |
  ::: /home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/viz-0.4.8/src/server/service.rs:18:1
   |
18 | pub struct ServiceMaker {
   | ----------------------- `ServiceMaker` defined here
```

**Comment by fundon** [comment]
@gbj It has been fixed.

**Comment by gbj** [comment]
Thanks for your work! I've merged this. I'll release a `leptos_viz` package as part of our little world of packages during the next release cycle, if that's all right with you.

**Pull request merged**
