### PR TITLE
Opt in locations in release mode with --cfg locations

### PR DESCRIPTION
**Pull request by zakstucke**

### CODE REVIEW

**Comment by zakstucke** [comment]
Are you happy with the name? Maybe it should be something leptos specific?

**Comment by zakstucke** [comment]
@gbj any chance of getting this one merged? Should be good to go other than any name bikeshedding 😁

**Comment by gbj** [comment]
Yep sorry — just read it over and this looks good to me.

As far as a name: Maybe something like `leptos_debuginfo` or `leptos_debug`?

**Comment by zakstucke** [comment]
No worries! Just switched it over to `leptos_debuginfo`

**Comment by gbj** [comment]
Thanks!

**Pull request merged**
