### PR TITLE
feat: add support for adding CSP nonces

### PR DESCRIPTION
**Pull request by gbj**
Addresses #1334.

### CODE REVIEW

**Comment by gbj** [comment]
So I've got this working for a super simple demo. Toggling the `nonce` feature on `leptos_actix` adds or removes a nonce. No need for app code to change in either case—if no nonce is present this works correctly, un-nonced, and if a nonce is present it injects the CSP meta tag and correct nonces.

I just need to get the Axum and Viz integrations up to parity with Actix.

I'm generating nonces in what I *think* is a legitimate way: filling 16 bytes (128 bits) with randomness generated by a `rand::ThreadRng`, then using `base64` to encode it in a URL-safe way. But I'm not at all an expert here.

```rust
#[component]
pub fn App(cx: Scope) -> impl IntoView {
    let csp = use_nonce(cx).map(|nonce| {
        view! { cx,
            <Meta
                http_equiv="Content-Security-Policy"
                content=format!("script-src 'nonce-{nonce}' 'unsafe-eval'")
             />
        }
    });

    view! { cx,
      {csp}
      <script nonce=use_nonce(cx)>"console.log('Hello, world!');"</script>
    }
}
```

**Comment by sebadob** [comment]
I just tested it and it is such a cool feature - I'm loving it!
This is quite a big boost for the security I would say.

And the way it is implemented now, it is almost trivial to set up even without any custom extractors / handlers / whatever.

Really cool! Thank you very much!

The 128 bit is a toally fine value as well, since they are re-generated with each request anyway. Anything longer would have a bigger performance impact.

**Comment by sebadob** [comment]
btw, for the documentation later on, a good default CSP would be something like this:

```
default-src 'self'; script-src 'strict-dynamic' 'nonce-{}'; style-src 'nonce-{}';
```

The `strict-dynamic` for the `script-src` is pretty nice. It basically means "If you are calling another inline script from a nonce'd script, accept it too, even without a nonce.

**Comment by gbj** [comment]
Oops my example created a hydration error due to the way the meta tag was created. This should work better
```rust
#[component]
pub fn App(cx: Scope) -> impl IntoView {
    provide_meta_context(cx);

    view! { cx,
        <p>"Test"</p>
        <Meta
            http_equiv="Content-Security-Policy"
            content=move || {
                use_nonce(cx)
                    .map(|nonce| {
                        format!(
                            "default-src 'self'; script-src 'strict-dynamic' 'nonce-{nonce}' \
                            'wasm-unsafe-eval'; style-src 'nonce-{nonce}';"
                        )
                    })
                    .unwrap_or_default()
            }
        />
        // manually insert nonce during SSR on inline script 
        <script nonce=use_nonce(cx)>"console.log('Hello, world!');"</script>
        // leptos_meta <Style/> and <Script/> automatically insert the nonce
        <Style>"body { color: blue; }"</Style>
    }
}
```

I'll merge this once the CI passes again.

**Comment by sebadob** [comment]
I thought this hydration error was because you needed to do some leftover work with axum and I did my test with axum actually.
Sorry, I should have commented this anyway. I saw an assertion panic on my side.

**Comment by sebadob** [comment]
And yes, with your new example, the error is gone! yay

**Comment by gbj** [comment]
All good, I'd initially been ignoring it too! :smile:

**Pull request merged**
