### PR TITLE
docs: added Callback to documentation and examples.

### PR DESCRIPTION
**Pull request by maccesch**
Also reduced code duplication in Callback implementation.

### CODE REVIEW

**Comment by maccesch** [comment]
@gbj The failing CI is not from my code

**Comment by gbj** [comment]
Thanks, looks great!

**Comment by maccesch** [comment]
Oh I now have the `Callback` before the `Fn()` option. I figured that after the discussons in Discord you'd probably want me to reverse that order?

**Comment by gbj** [comment]
Don't worry about it, I can go in and rearrange them if I'd like!

**Pull request merged**
