### PR TITLE
fix: fix `web-sys` warnings in `server_fn`

### PR DESCRIPTION
**Pull request by sabify**
This needs to be merged first before #2827 to make CI work.

### CODE REVIEW

**Comment by sabify** [comment]
I made separate PRs to address the update issues. This PR and #2827 will solve the issues. Would you mind to combine them in single PR?

The other problem is that the `cargo binstall wasm-bindgen-cli` still fetches the old `wasm-bindgen-cli` binary (v0.9.92) and most of the examples won't compile.

https://github.com/leptos-rs/leptos/actions/runs/10377904297/job/28733123057?pr=2828#step:20:1103

Do you know if there is any caching layer that CI's `binstall` doesn't get the latest binary?

**Review by benwis — APPROVED** [review]

**Comment by benwis** [comment]
You beat me to it. I think cargo-binstall will only use the latest binaries, which are only generated when a new version is released. Which I'll be arranging now alongside cargo-leptos

**Comment by benwis** [comment]
@sabify Would you like to make the same changes to the leptos_0.6 branch? This only fixes it for those on git main

**Comment by sabify** [comment]
> @sabify Would you like to make the same changes to the leptos_0.6 branch? This only fixes it for those on git main

Sure. Just waiting for the green CI.

**Comment by benwis** [comment]
I'm going to merge this, the CI will be red until I release cargo-leptos

**Comment by benwis** [comment]
@sabify Merged, and cargo-leptos has been released

**Pull request merged**
