### PR TITLE
draft for sso_auth_session example

### PR DESCRIPTION
**Pull request by sjud**
Draft for an Example for SSO auth, based on conversation with Benwis & diversable. Please give all nits, thank you for your feedback.

### CODE REVIEW

**Comment by sjud** [comment]
halp
```
    Installed package `cargo-all-features v1.10.0` (executables `cargo-build-all-features`, `cargo-check-all-features`, `cargo-test-all-features`)
[cargo-make] INFO - Execute Command: "rustup" "run" "nightly" "cargo" "+nightly" "build-all-features"
error: no such command: `+nightly`

	Cargo does not handle `+toolchain` directives.
	Did you mean to invoke `cargo` through `rustup` instead?
[cargo-make] ERROR - Error while executing command, exit code: 101
[cargo-make] WARN - Build Failed.
Error: Process completed with exit code 1.
```

**Comment by sebadob** [comment]
I have not looked into the code too much (short on time today), but I saw you refer to google SSO there.
You could, if you like, integrate [Rauthy](https://github.com/sebadob/rauthy) to have a fully self-contained example.
I do have created a [minimal client](https://github.com/sebadob/rauthy/tree/main/rauthy-client) as well from which you could just grab some code, if you like.

**Comment by sjud** [comment]
> I have not looked into the code too much (short on time today), but I saw you refer to google SSO there. You could, if you like, integrate [Rauthy](https://github.com/sebadob/rauthy) to have a fully self-contained example. I do have created a [minimal client](https://github.com/sebadob/rauthy/tree/main/rauthy-client) as well from which you could just grab some code, if you like.
> 
> You could actually add Rauthy directly and push a pre-configured SQLite database to the example, which would even mean way less setup.

That looks like a cool project! I'll check that out. Thanks :)

**Comment by erlend-sh** [comment]
Prior art by @kerkmann might also be useful here: https://crates.io/crates/leptos_oidc

It’s already been tested with Rauthy as well.

**Comment by kerkmann** [comment]
Thanks @erlend-sh , thanks for mentioning it! :heart: 

@sjud Yes, if you need some help or some knowledge sharing, just contact or ping me. :3

**Comment by benwis** [comment]
@sjud Do you think this is ready for merging?

**Comment by sjud** [comment]
Ya let’s merge. We all have bigger fish to fry and the code works.

**Pull request merged**
