### PR TITLE
"#two" was being hidden. Added another # to unhide

### PR DESCRIPTION
**Pull request by he00741098**
Screenshot 2023-10-05 8 22 02 AM

Screenshot 2023-10-05 8 23 01 AM

### CODE REVIEW

**Comment by gbj** [comment]
Thanks! But this fix makes it appear as `two`, when it should be `#two` I think? I guess it's a peril of trying to display CSS inside Rust inside Markdown... 

Who knows, maybe a third `#`? Or some kind of escape?

**Comment by he00741098** [comment]
image

That is strange. For some reason when I run `mdbook serve`, the `#` is still present

**Comment by he00741098** [comment]
Looking back at this, perhaps you were confused by the 2 pictures I initially added. I was just trying to demonstrate that the line was hidden. I should have clarified that the two pictures were both of the actual book and the hide/unhide feature of mdbook.

**Comment by gbj** [comment]
My bad! I just looked at your second image and thought it was after the fix, hadn't run mdbook myself. Thanks for this fix, I'll merge it.

**Pull request merged**
