### PR TITLE
fix: run `autofix.ci` on pull requests only

### PR DESCRIPTION
**Pull request by sabify**
Related: https://github.com/leptos-rs/leptos/pull/3235#issuecomment-2471376458

### CODE REVIEW

**Comment by benwis** [comment]
I did and it still seems to have no access. But there's literally a check mark on the app's page that says it does have access

**Comment by sabify** [comment]
Nothing's wrong with permissions. I just asked to rerun the `autofix.ci` workflow in this PR.

**Comment by sabify** [comment]
It works. Hope it helps.

**Comment by benwis** [comment]
I really appreciate all the CI improvements, thanks sabify

**Pull request merged**
