### PR TITLE
test(ci): check semver

### LINKED ISSUE #2229: CI: explore adding `cargo-semver-checks`
**Is your feature request related to a problem? Please describe.**
I'd like additional help from CI in identifying possible breaking API changes in PRs.

**Describe the solution you'd like**
Adding [`cargo-semver-checks`](https://lib.rs/crates/cargo-semver-checks) as part of CI won't catch every possible breaking change, but could be an extra layer of protection.

Open to other thoughts!

### PR DESCRIPTION
**Pull request by agilarity**
Resolves #2229

See the semver output [here](https://github.com/leptos-rs/leptos/actions/runs/8395834544/job/22995978008).

### CODE REVIEW

**Comment by benwis** [comment]
@agilarity Is this ready for merging?

**Comment by agilarity** [comment]
> @agilarity Is this ready for merging?

Yes.

**Comment by benwis** [comment]
Thank you!

**Comment by benwis** [comment]
@agilarity Can you take a look at the CI? Seems cargo-semver-checks is failing

**Pull request merged**
