### PR TITLE
Tailwind example update

### PR DESCRIPTION
**Pull request by SleeplessOne1917**
I noticed that some of the tailwind examples weren't leveraging `cargo-leptos`'s built-in support for tailwind. This PR rectifies that.

### CODE REVIEW

**Comment by LetrixZ** [comment]
Is it possible to watch the `tailwind.css` file?

**Comment by SleeplessOne1917** [comment]
Yes. This removes the need for running tailwind in watch mode in another terminal session.

**Comment by LetrixZ** [comment]
What I meant by that, how can I make changes to that file and have the changes show without restarting cargo-leptos?

**Comment by SleeplessOne1917** [comment]
[From the part of cargo-leptos`s docs regarding site paramaters](https://github.com/leptos-rs/cargo-leptos#site-parameters):
```toml

# The tailwind input file.
#
# Optional, Activates the tailwind build
tailwind-input-file = "style/tailwind.css"

# The tailwind config file.
#
# Optional, defaults to "tailwind.config.js" which if is not present
# is generated for you
tailwind-config-file = "tailwind.config.js"
```

The presence of the `tailwind-input-file` param tells cargo leptos to watch for changes in tailwind styles as well as the leptos code. This also eliminates the need for the `style-file` param.

**Comment by LetrixZ** [comment]
Tried with both examples (`cargo leptos watch`).
Declared a style in `tailwind.css` but nothing happens until I restart cargo-leptos.
Changes in the view code are being watched but not in the input file.

**Comment by SleeplessOne1917** [comment]
I was able to see changes by refreshing the browser as opposed to killing and restarting the watch.

**Pull request merged**
