### PR TITLE
feat(leptos-config): kebab-case via serde's rename_all

### PR DESCRIPTION
**Pull request by filipdutescu**
Currently, `leptos::LeptosOptions` are deserialized (and serialized) to `snake_case`, since, by default, `serde` uses the name of the field as-is. The options given via `.toml` files are given using `kebab-case`. This behaviour leads to problems if you wish to use `leptos::LeptosOptions` as the type of a field in your own config, which uses the `kebab-case` syntax, as it will not provide any values to that field.

These changes switch out the previous mechanism of manually replacing the `-` character to the `_` character in order for serialization to work. In its place, it uses `serde`'s `#[serde(rename_all = ...)]` macro to handle the naming convention.

In case other naming conventions are used, a workaround would be to define a user-owned mirror struct of `leptos::LeptosOptions`, which would contain the required fields, deserialize it as desired and' convert it to the latter via, for example, the `From<T>` trait.

Closes: #1295

### CODE REVIEW

**Comment by filipdutescu** [comment]
should I also add defaults for `serde` deserialization? same as the `config-rs` ones

**Comment by gbj** [comment]
This looks good to me, overall. 

Two things:
1. Could you revert the changes to `examples/todo_app_sqlite/Todos.db`? I assume this was just due to testing that example but the sqlite database changes got committed.

> should I also add defaults for `serde` deserialization? same as the `config-rs` ones
2. Yes, defaults would be great! I think the default values for fields that can have them are listed in the `typed-builder` macro annotations on each field.

**Comment by filipdutescu** [comment]
Hopefully that should be it. Please let me know if I should make further changes! :grin:

**Comment by gbj** [comment]
Looks good to me!

**Pull request merged**
