### PR TITLE
doc: more details on how redirect works (#2789)

### PR DESCRIPTION
**Pull request by metatoaster**
Include the note about blocking resource for both the actix and axum, and expanded the wording on the axum version.

Note that I did add a `FIXME` note to `leptos_axum::redirect` because I don't know how should this be properly addressed in the documentation (or the code for that matter).

I am open to suggestion to better wording, etc.

### CODE REVIEW

**Comment by gbj** [comment]
Thanks! I split it into two sections, one describing usage and one with more depth about the implementation (what you wrote). Hopefully this will point others in the right direction if they are using curl etc.

**Comment by metatoaster** [comment]
Thanks for that. Looking into the `serverfnredirect` header I found myself inside `server_fn/src/redirect.rs`, and it provides these hooks and I see that by default it is set for the various form components (i.e. `ActionForm` and `MultiActionForm`).  This means if the component that calls the function that will do the redirect will also need to set this hook up much like those components did?  I will note that those sections are prefixed with

```rust
// if redirect hook has not yet been set (by a router)`
```

It may be useful to also include a reference from the redirect functions too to lead to the explanation on how this bit actually works, as what ended up happening when I first came across this was that I more or less re-invented the wheel by setting the 302 status code directly immediately after the server function call (after checking whether that function returned an `Ok(Err(...))` to indicate that a redirect is needed.  Granted what I did works but it would be useful to have something more canonical/idiomatic for this package that uses the provided pieces.  All that being said, with these pieces I've found I may take yet another stab at wrapping up this problem.

**Comment by gbj** [comment]
> Thanks for that. Looking into the `serverfnredirect` header I found myself inside `server_fn/src/redirect.rs`, and it provides these hooks and I see that by default it is set for the various form components (i.e. `ActionForm` and `MultiActionForm`).

Correct: This is so that they still work outside the `Router` (for example, if you use them with islands and there is no client-side routing)

> This means if the component that calls the function that will do the redirect will also need to set this hook up much like those components did? I will note that those sections are prefixed with

The user should not need to set these manually, unless they are not using the router. I notice that `leptos_router` does not currently call `set_redirect_hook`, which it should – that is just a bug, not something that users should need to think about.

**Comment by metatoaster** [comment]
I see, and digging around further I found [this TODO note in `router/src/components.rs`](https://github.com/leptos-rs/leptos/blob/27dbadb7d2/router/src/components.rs#L90).  I hope the relevant hooks will be in place and fully set up for the final 0.7 release.

**Comment by gbj** [comment]
See #2815.

**Pull request merged**
