### PR TITLE
Deprecate the `path` argument in the relevant `LeptosRoutes` trait methods.

### PR DESCRIPTION
**Pull request by gibbz00**
```rust
let app = Router::new()
    .leptos_routes(&leptos_options, generate_route_list(app), app)
// ...
```
becomes 

```rust
let app = Router::new()
    .leptos_routes(&leptos_options, app)
// ...
```

Might be too much of a breaking change for such a subjective improvement. I'll refrain from sending in a PR updating `start_axum` until this change is deemed appropriate. 😊

### CODE REVIEW

**Comment by gbj** [comment]
I'm open to making a change this like in the future. As far as I can tell it would break ~100% of Leptos-Axum apps so of course it's not changeable until the next version. I am also not sure the churn of breaking everything is worth the benefit of saving 20 characters or so, but I'm open to being wrong.

**Comment by gibbz00** [comment]
Spot on. Thought about mentioning that it could alternatively be added to the 0.6 milestone, but seems like you're way ahead of me :) Another option could also be to hold on until a major version is released that would require fixing ~100% of the packages regardless.

I'll make sure to fix the examples as well as the starter crate tomorrow for completeness’ sake.

**Comment by gibbz00** [comment]
Hey again, 

I went ahead to made the changes consistent in the `viz` and `actix` routers, as well as opening up fix PRs in the respective starter repos. More so to not keep an incomplete PR lying around, and not to as a means to push for it being merged right away. I would be fully understanding if you choose to close this whenever, given previous discussions ✌️

**Comment by benwis** [comment]
The reason to do this is to allow people to pass in some routes, but not all routes, for automatic route generation in LeptosRoutes. Moving it inside saves props, sure, but also removes the ability to handle them seperately

**Comment by gibbz00** [comment]
Hi @benwis!

Could you give me an example for when/how it would be useful? You're probably on to something, it's more that I lack the experience to understand when that could be utilized 🙈

**Comment by benwis** [comment]
Sure, let's say you wanted to apply an Axum middleware like TraceLayer, CompressionLayer, or some kind of auth thing, to specific routes in your app, kinda like so
```rust
let router = Router
.route("/compressme", get(handler))
.layer(CompressionLayer::new())
```
because LeptosRoutes will automatically find all routes in your Leptos app, and you can't have conflicting routes, you first have to exclude the route from general handling
```rust
let routes = generate_route_list_with_exclusions("/compressme")
// then pass the routes to LeptosRoutes via the path param
```

**Comment by gibbz00** [comment]
Ahh, well put.

`leptos_routes_with_handler()` still exists. Would it be possible to use it for that use case?

https://github.com/leptos-rs/leptos/blob/a8e25af5233bb014d3cee85e4e9be8b3e4586de9/integrations/axum/src/lib.rs#L1437-L1445
https://github.com/leptos-rs/leptos/blob/a8e25af5233bb014d3cee85e4e9be8b3e4586de9/examples/session_auth_axum/src/main.rs#L91-L93

**Comment by benwis** [comment]
It has a different usecase, it's meant mostly to let people provide their own context. Unfortunately, at least for the idea of middleware support, I don't think you could apply that. You'd have to do per handler middleware instead of layer middleware. Something to think about though

**Comment by benwis** [comment]
In the interest of maintaining flexibility and now with server fn routes being added to the macro, we'll need to preserve the path var. Thanks for making the PR and having the conversation!

**Pull request closed without merging**
