### PR TITLE
added hashes generated from cargo-leptos

### PR DESCRIPTION
**Pull request by maccesch**
This is accompanying PR for https://github.com/leptos-rs/cargo-leptos/pull/256

### CODE REVIEW

**Comment by benwis** [comment]
Overall this looks pretty good, my question would be what would happen if you were not using cargo-leptos? We still want to maintain compatibility with that use case

**Comment by maccesch** [comment]
I believe that shouldn't be a problem. The server code looks if the hash.txt exists and only if it does adds the hashes to the file names.

**Comment by maccesch** [comment]
The failing check doesn't seem to be from my code

**Comment by BrandonDyer64** [comment]
Any way this gets backported to leptos 6?

**Comment by maccesch** [comment]
This was done for Leptos 0.6 👍🏼

**Pull request merged**
