### PR TITLE
feat: add method to RouteContext (#1808)

### LINKED ISSUE #1808: Add `RouteContext::method`
**Is your feature request related to a problem? Please describe.**
Since `Route` has a method attribute, it would be nice to have a way to use this value inside components.

**Describe the solution you'd like**

App.rs
```
<Route
    path="/path"
    methods=&[Method::Get, Method::Post]
    view=Page />
```

Page.rs
```rust
pub fn Page() -> impl IntoView {
    let route = use_route();

    match route.method() { // <----- This feature request
        Method::Get => todo!(),
        Method::Post => todo!(),
        _ => unreachable!(),
    };

    view! {
        // ...
    }
}
```

### PR DESCRIPTION
**Pull request by zoomiti**
Closes #1808

### CODE REVIEW

**Comment by zoomiti** [comment]
@yokomizer is this a solution that works for your use case?

**Comment by zoomiti** [comment]
This is the second time `server_fn` has failed to run its CI on my PR's. I want to look into this

**Comment by gbj** [comment]
@zoomiti The server fn CI issue is just that there are now so many features to enable all the encodings that, when the CI runs, it runs out of space checking all the combinations. We just need to disable some of the feature combos and it will be fine.

**Comment by zoomiti** [comment]
I forgor to add docs to the new method

**Comment by gbj** [comment]
Thanks, this looks great! A clever way of handling it that I had not thought of (providing it via context, on the server). :tada:

**Comment by zoomiti** [comment]
Unless I'm wrong I thought this was your idea! 
https://github.com/leptos-rs/leptos/issues/1808#issuecomment-1925499364

**Pull request merged**
