### PR TITLE
`Cargo.lock`

### PR DESCRIPTION
**Pull request by sabify**
Closes https://github.com/leptos-rs/leptos/issues/2881

### CODE REVIEW

**Comment by sabify** [comment]
I have excluded examples, projects and benchmarks to prevent PR pollution from Depdendabot. Please let me know if you need any of them to be included.

**Comment by sabify** [comment]
Failed CIs are not related to this PR.

**Comment by benwis** [comment]
I am confused why unused functions would cause compilation to fail, isn't that usually a warning?

**Comment by gbj** [comment]
The dead code warning causes failures because we have CI set to fail on clippy warnings. This has been fixed on main so will not be an issue here.

Looks good, and thanks for taking the time!

**Pull request merged**
