### PR TITLE
New example: session_auth_axum

### PR DESCRIPTION
**Pull request by j0lol**
New example using axum_sessions_auth for managing user authentication, based on the todo example.

### CODE REVIEW

**Comment by gbj** [comment]
Thanks — I added it to our CI testing and I had to fix a few imports in `main.rs` to get it running.

On first load I find that I get
```
Server Error: error running server function: Pool missing.
```
If I've done something like log in, or log out, or navigate to another page and back, I don't get this... But if I reload, I do on first SSR. I wonder if it's some kind of a race condition where it's not being provided initially?

**Comment by j0lol** [comment]
thats odd? i'm not sure what's wrong..

**Comment by j0lol** [comment]
I should probably add errorboundraries to the rest of the forms...

**Comment by gbj** [comment]
I think there are some fixes you made that I don't think you've pushed yet. Were there any other changes you wanted to make?

**Comment by j0lol** [comment]
missed the comment, ill merge my fixes now :)

**Comment by j0lol** [comment]
all good now!

**Comment by gbj** [comment]
Thanks — looks good!

**Pull request merged**
