### PR TITLE
Minor: doclink to Error needed FQDN.

### PR DESCRIPTION
**Pull request by martinfrances107**
Fixed warning  seen whilst running 

```bash
Cargo doc
```

### CODE REVIEW

**Comment by gbj** [comment]
Hm, interesting. I think it's *supposed* to refer to the `Error` struct defined immediately below. Is it perhaps ambiguous because I see to be importing `thiserror::Error` for no obvious reason?

https://github.com/leptos-rs/leptos/blob/c1991858081c0e8dd7aed590f44ce8b62ebf57fd/server_fn/src/error.rs#L8-L14

**Comment by martinfrances107** [comment]
>  think it's supposed to refer to the Error struct defined immediately below

Opps  I also now  think you are correct 

I will fix this up... one sec..

**Comment by martinfrances107** [comment]
fixed

**Comment by gbj** [comment]
Thanks!

**Pull request merged**
