### PR TITLE
Allow for documentation and other attributes to fields in server fn

### LINKED ISSUE #2844: Server function param custom name
**Is your feature request related to a problem? Please describe.**
[Cloudflare Turnstile](https://developers.cloudflare.com/turnstile/) (CAPTCHA) injects a form `<input>` that has the name `cf-turnstile-response` which isn't a valid rust ident.
When using the `<ActionForm/>` (important for progressive degradation) I would need to do this, which obviously isn't possible:
```rust
#[server]
async fn signup(username: String, email: String, cf-turnstile-response: String) -> Result<_, _> {}
```

**Describe the solution you'd like**
A serialization rename attribute for server function params.
```rust
#[server]
async fn signup(
    username: String,
    email: String,
    #[server(rename = "cf-turnstile-response")]
    cf_turnstile_response: String,
) -> Result<_, _> {}
```

**Describe alternatives you've considered**
I'm realizing now that there is a `data-response-field-name` attribute that will override the form param name on the client side, so I'm unblocked on this. However, I still think this would be a useful feature for those times when it isn't possible.

### PR DESCRIPTION
**Pull request by rakshith-ravi**
Fixes #2844

### CODE REVIEW

**Comment by rakshith-ravi** [comment]
Yet to test this out properly, so take this PR with a grain of salt

**Comment by rakshith-ravi** [comment]
Yup. Tested it out and it compiles

**Comment by gbj** [comment]
Thanks! This looks good overall but I think it can actually me slightly more permissive. 

For example:
```rust
#[server]
pub async fn add_todo(
    /// The actual content of the todo.
    #[server(default)]
    #[server(rename = "someOtherName")]
    title: String,
    #[allow(unused)] foo: usize,
) -> Result<(), ServerFnError> {
```
Will reject the `#[allow(unused)]`, which is fine in a normal fn definition.

Basically I think 
1) the error condition should be moved up into the `if attr.path().is_ident("server") {` branch: if it is `#[server]` and it's not `default` or `rename`, then it should return an error
2) then the `else` branch can simply pass through *all* other attributes, not just `doc`

Does that make sense?

(The rename looks fine to me and I think you can remove the comment about it!)

Thanks very much for this.

**Comment by rakshith-ravi** [comment]
That makes sense, but wouldn't we want to control the list of attributes that are passed to the struct? My concern is that an end user might not know what happens behind the scenes in the server fn macro, so they might not know what attributes are allowed and what are not, thereby causing confusion when they try to use a macro but it ends up failing

**Comment by rakshith-ravi** [comment]
Got it. Will compile a list of commonly used attributes and get them added

**Comment by gbj** [comment]
lgtm, thank you!

**Pull request merged**
