### PR TITLE
Test business logic for counter_without_macros

### PR DESCRIPTION
**Pull request by agilarity**
This demonstrates extracting and testing business logic.

Run `cargo make test-all` from the `examples/counter_without_macros` directory

You can also run `cargo make test-examples` from the `leptos/examples` directory.

### CODE REVIEW

**Comment by gbj** [comment]
Thanks. I like what you're doing but have two questions
1. What's up with the casting back and forth between `i32` and `u32`?
2. It looks like you create the `Count` struct and its logic but don't actually use it in the component, unless there's a missing commit or something. You should be able to use `Count` to handle the actual logic in the component: create the signal with an initial `Count` value, call `.increase()` and `.decrease()` in the click handlers, etc. I think this would make more sense of the added testing.

**Comment by agilarity** [comment]
Oops!

That's my mistake on both.

I will fix it.

Thank you for the considerate feedback.

**Comment by agilarity** [comment]
I have pushed up the missing use of the `Count`.

Only one cast is to prevent a negative `step` value.

Thank you for catching the problems.

**Comment by gbj** [comment]
Looks good, thanks!

**Pull request merged**
