### PR TITLE
Update counter example's signal usage

### PR DESCRIPTION
**Pull request by dfee**
Seems we're missing `.set()`

### CODE REVIEW

**Comment by gbj** [comment]
Unless I'm badly mistaken, this is just a well-documented difference between the nightly and stable features of this library. Could you please clarify the issue you're trying to fix?

**Comment by dfee** [comment]
Reproducing the `counter` demo outside of your test repo, gives me the following error:
```
$ just build
trunk build
2024-03-25T15:36:00.237841Z  INFO 🚀 Starting trunk 0.18.8
2024-03-25T15:36:00.238987Z  INFO 📦 starting build
2024-03-25T15:36:00.239975Z  INFO spawning asset pipelines
2024-03-25T15:36:00.330380Z  INFO copying & hashing icon path="public/favicon.ico"
2024-03-25T15:36:00.330534Z  INFO building edge
2024-03-25T15:36:00.331499Z  INFO finished copying & hashing icon path="public/favicon.ico"
   Compiling edge v0.1.0 (/home/code/edge)
error[E0618]: expected function, found `WriteSignal<i32>`
  --> src/lib.rs:17:39
   |
13 |     let (value, set_value) = create_signal(initial_value);
   |                 --------- `set_value` has type `WriteSignal<i32>`
...
17 |             <button on:click=move |_| set_value(0)>"Clear"</button>
   |                                       ^^^^^^^^^---
   |                                       |
   |                                       call expression requires function

For more information about this error, try `rustc --explain E0618`.
error: could not compile `edge` (lib) due to 1 previous error
2024-03-25T15:36:00.923265Z ERROR ❌ error
error from build pipeline

Caused by:
    0: HTML build pipeline failed (1 errors), showing first
    1: error from asset pipeline
    2: error during cargo build execution
    3: cargo call to executable 'cargo' with args: '["build", "--target=wasm32-unknown-unknown", "--manifest-path", "/home/code/edge/Cargo.toml"]' returned a bad status: exit status: 101
Error: error from build pipeline

Caused by:
    0: HTML build pipeline failed (1 errors), showing first
    1: error from asset pipeline
    2: error during cargo build execution
    3: cargo call to executable 'cargo' with args: '["build", "--target=wasm32-unknown-unknown", "--manifest-path", "/home/code/edge/Cargo.toml"]' returned a bad status: exit status: 101
error: Recipe `build` failed on line 3 with exit code 1
```

changing to `.set(0)` passed. I'm sure there's documentation somewhere – you say so – but I'm unclear on what I've missed.

**Comment by dfee** [comment]
fwiw:
```toml
$ cat Cargo.toml
[package]
name = "edge"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[profile.release]
codegen-units = 1
lto = true

[dependencies]
console_error_panic_hook = "0.1.7"
console_log = "1.0.0"
leptos = { version = "0.6.9", features = ["csr"] }
log = "0.4.21"

[dev-dependencies]
wasm-bindgen = "0.2.92"
wasm-bindgen-test = "0.3.42"
web-sys = "0.3.69"
```

**Comment by dfee** [comment]
Ah, from the `README`.
```
The nightly feature enables the function call syntax for accessing and setting signals, as opposed to .get() and .set(). This leads to a consistent mental model in which accessing a reactive value of any kind (a signal, memo, or derived signal) is always represented as a function call. This is only possible with nightly Rust and the nightly feature.
```

**Comment by dfee** [comment]
Also note:
```
$ rustc --version
rustc 1.79.0-nightly (2f090c30d 2024-03-23)
```

🤷

**Comment by gbj** [comment]
FWIW the issue here was just that the `nightly` feature on the `leptos` crate is not enabled. There's some [discussion here](https://book.leptos.dev/getting_started/index.html#hello-world-getting-set-up-for-leptos-csr-development) that expands on the note in the README.

**Pull request closed without merging**
