### PR TITLE
fix: update `wasm-bindgen` and `web-sys` for leptos 0.6

### PR DESCRIPTION
**Pull request by sabify**

### CODE REVIEW

**Comment by benwis** [comment]
Looks good to me, kinda sucks our CI will only run on one branch

**Comment by sabify** [comment]
The CI is happy: https://github.com/sabify/leptos/actions/runs/10378642460

**Comment by benwis** [comment]
> The CI is happy: https://github.com/sabify/leptos/actions/runs/10378642460

How did you get it to do that?

**Comment by sabify** [comment]
I ran the CI on my fork.

**Pull request merged**
