### PR TITLE
Nix Shell

### PR DESCRIPTION
**Pull request by pelasgus**
Includes trunk; Installing trunk via cargo on Nix breaks after a few gcs

### CODE REVIEW

**Comment by tsimouris** [comment]
There are currently some issues with the current configuration; will get on it tomorrow

**Comment by rambip** [comment]
you can already use `nix develop` if you have flakes.
Just add it to `flake.nix` in `mkShell`

You could also add `cargo make`

**Comment by benwis** [comment]
Yeah, I mean I'm not really against adding a nix-shell file, but it seems like most Nix projects I see are using the flake.nix file, and @rambip has a workaround for nix-shell. @pelasgus does that work for you?

**Comment by benwis** [comment]
I'm going to close this for now, as it seems like most Nix projects use flakes.

**Pull request closed without merging**
