### PR TITLE
MSRV Bump to 1.80.0, drop crate lazy_static and use std::sync::LazyLock.

### PR DESCRIPTION
**Pull request by martinfrances107**
#2726

### CODE REVIEW

**Comment by martinfrances107** [comment]
Sorry for the commit spree ... finally found the path out of the woods.

**Comment by sabify** [comment]
Examples and benchmarks are excluded from the workspace and bumping the MSRV in the workspace is nonsense here. You may add MSRV to each example's `Cargo.toml`, not the workspace.

**Comment by martinfrances107** [comment]
> You may add MSRV to each example's Cargo.toml, not the workspace.

Ok ... change is comming

**Review by rakshith-ravi — APPROVED** [review]
Been sitting on this for a week. I think it shouldn't be the biggest problem to upgrade MSRV. Looks good to me.

@martinfrances107 you might want to hold off on the merge conflict resolution until we get a consensus about upgrading MSRV, lest I'm worried we end up wasting your time.

**Comment by martinfrances107** [comment]
>you might want to hold off on the merge conflict resolution until we get a consensus about upgrading MSRV

Understood - It only took me a short time to reconstruct the PR .. force push is comming

**Comment by benwis** [comment]
I don't see a problem with doing this, especially for 0.7 as a major release. We don't really have a stated MSRV policy. Appreciate you taking the time @martinfrances107

**Pull request merged**
