### PR TITLE
feat: add `autofix.ci` to address formatting issues and possible clippy fixes

### PR DESCRIPTION
**Pull request by sabify**

### CODE REVIEW

**Comment by autofix-troubleshooter** [comment]
Hi! I'm the <a href="https://autofix.ci">autofix logo<strong>autofix.ci</strong></a> troubleshooter bot.

It looks like you correctly set up a CI job that uses the autofix.ci GitHub Action, but the [**autofix.ci GitHub App**](https://github.com/apps/autofix-ci/) has not been installed for this repository. This means that autofix.ci unfortunately does not have the permissions to fix this pull request. If you are the repository owner, please install the app and then restart the CI workflow! 😃

**Comment by benwis** [comment]
I love the idea of this, but I'm somewhat torn because it's got a very small number of installs.

**Comment by sabify** [comment]
I believe we are giving it read access. I don't understand the installs counter shown in github apps, but some pretty big repos are also using it (from https://github.com/autofix-ci/action/network/dependents):

https://github.com/jdx/mise/blob/main/.github/workflows/autofix.yml
https://github.com/rolldown/rolldown/blob/main/.github/workflows/autofix.yml
https://github.com/react-navigation/react-navigation/blob/main/.github/workflows/autofix.yml
and ...

**Comment by sabify** [comment]
Cool! Have you installed on this repo?

> Hi! I'm the [autofix logo**autofix.ci**](https://autofix.ci) troubleshooter bot.
> 
> It looks like you correctly set up a CI job that uses the autofix.ci GitHub Action, but the [**autofix.ci GitHub App**](https://github.com/apps/autofix-ci/) has not been installed for this repository. This means that autofix.ci unfortunately does not have the permissions to fix this pull request. If you are the repository owner, please install the app and then restart the CI workflow! 😃

**Comment by benwis** [comment]
Yes, I did

**Comment by sabify** [comment]
https://github.com/leptos-rs/leptos/runs/32883145624

There should be permission issue here that it can not open PR for the fix.

**Comment by benwis** [comment]
Github isn't that granular. It has the permissions it asked for and I can't give it more

**Comment by sabify** [comment]
Ooops! Changes cannot be applied to the main branch as we don't give it write permission and it will not open PRs for that.

We have three options here:

1. Give it write access to apply changes.
2. Comment out running on the main branch. Will run only on PRs.
3. Just leave it as it is to acknowledge that there may be some issues in the codebase with the clippy and rustfmt.

**Comment by benwis** [comment]
I think running only on PRs makes sense here, that's the real pain point anyway

**Pull request merged**
